### ISSUE TITLE
@DillyPickle broke ruby ore loot table

### ISSUE THREAD

**Issue by PurplePineaapple** [PurplePineaapple/AdishirsMod#13]
When you were trying to make sapphire loot talbe you accidentally deleete d this: 

![image](https://user-images.githubusercontent.com/76782952/112531482-9f67c480-8d75-11eb-87d8-13b9ceb51170.png)
i fixed it but dont screw something else in the future lmao

**Comment by PurplePineaapple** [comment]
Fixed

**Comment by DillyPickle** [comment]
They wernet broken for me lmao
