### ISSUE TITLE
ERROR in BlockInit

### ISSUE THREAD

**Issue by DillyPickle** [PurplePineaapple/AdishirsMod#14]
There is a error in the blockinit file

**Comment by PurplePineaapple** [comment]
Where?

**Comment by DillyPickle** [comment]
![image](https://user-images.githubusercontent.com/67352634/112550960-2a54b900-8d8e-11eb-917a-dc1f458c3f02.png)

**Comment by PurplePineaapple** [comment]
I dont have that error i think there was something wrong with the commit it didnt commit OrangeTreeLog.java

**Comment by DillyPickle** [comment]
that is the issue
