### ISSUE TITLE
New EndMob?

### ISSUE THREAD

**Issue by PurplePineaapple** [PurplePineaapple/AdishirsMod#4]
Any ideas for an end mob?

___
_Requested by @Adishir_

**Comment by DillyPickle** [comment]
I think a end spider or something would be cool.

**Comment by PurplePineaapple** [comment]
Hmm maybe. Btw @DillyPickle are the webhooks working on the discord server? I can't go on discord rn.

**Comment by Adishir** [comment]
We could do something like flying. but that might get *shot down*
